import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const metadata: Metadata = {
  title: {
    default: "EDENBACO | Agence de Sécurité et Gardiennage au Maroc",
    template: "%s | EDENBACO",
  },

  description:
    "EDENBACO est une agence spécialisée dans la sécurité privée, le gardiennage et la protection des biens et des personnes au Maroc. Solutions de sécurité fiables et professionnelles.",

  keywords: [
    "EDENBACO",
    "agence de sécurité",
    "gardiennage Maroc",
    "sécurité privée Maroc",
    "agents de sécurité",
    "protection des biens",
    "sécurité entreprise",
    "sécurité événementielle",
    "Casablanca",
    "Marrakech",
    "Rabat",
    "sécurité Maroc",
  ],

  authors: [{ name: "EDENBACO" }],
  creator: "EDENBACO",

  openGraph: {
    title: "EDENBACO | Agence de Sécurité au Maroc",
    description:
      "Services de sécurité privée, gardiennage et protection des sites et des personnes.",
    url: "sec-maroc.vercel.app",
    siteName: "EDENBACO",
    images: [
      {
        url: "/og-image.png",
        width: 1200,
        height: 630,
        alt: "EDENBACO Sécurité",
      },
    ],
    type: "website",
  },

  twitter: {
    card: "summary_large_image",
    title: "EDENBACO | Sécurité et Gardiennage",
    description: "Agence de sécurité privée et protection au Maroc.",
    images: ["/og-image.png"],
  },

  icons: {
    icon: "/favicon.ico",
  },

  metadataBase: new URL("https://sec-maroc.vercel.app"),
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="fr"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
